// ============================================================================
// Check-out bill — final guest invoice PDF
// ============================================================================
// S3h. Generates the printable bill the receptionist hands to the guest
// at check-out. Pulls from:
//   · booking            — stay summary, dates, room, nightly rate
//   · booking_charges    — every folio line (paid + unpaid)
//   · guest_vouchers     — used vouchers (qty_consumed > 0) as $0
//                           audit lines so the guest sees what they got
//   · voucher_consumptions — granular detail per redemption
//
// Layout mirrors the TM30 generator (src/lib/tm30.js):
//   · A4 portrait, STAYLO brand band at top
//   · 1. Stay summary       — booking ref, dates, nights, room
//   · 2. Room charges       — nightly rate × nights
//   · 3. Extra charges      — folio lines grouped by category
//   · 4. Vouchers redeemed  — list with $0 each (so the guest sees
//                              the value of perks received)
//   · 5. Total              — subtotal − vouchers value (if any) + tax
//   · Footer                — "Generated by STAYLO" stamp + booking ref
//
// Returns a Uint8Array. Use downloadCheckoutBill() to trigger a
// browser download in one call.
// ============================================================================
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

// STAYLO brand colours.
const DEEP    = rgb(0.10, 0.12, 0.18) // #1A1F2E
const ORANGE  = rgb(1.00, 0.42, 0.00) // #FF6B00
const PINK    = rgb(1.00, 0.24, 0.71) // #FF3CB4
const ELECTRIC = rgb(0.42, 0.36, 0.91) // #6C5CE7
const LIBRE   = rgb(0.00, 0.72, 0.58) // #00B894
const GRAY    = rgb(0.45, 0.45, 0.48)
const LIGHT   = rgb(0.97, 0.96, 0.94)

const A4 = { width: 595.28, height: 841.89 }
const MARGIN = 40

const t = v => v == null ? '' : String(v)

function fmtDateISO(iso) {
  if (!iso) return ''
  const d = new Date(typeof iso === 'string' && iso.length === 10 ? iso + 'T00:00:00Z' : iso)
  if (isNaN(d)) return t(iso)
  const dd = String(d.getUTCDate()).padStart(2, '0')
  const mm = String(d.getUTCMonth() + 1).padStart(2, '0')
  const yyyy = d.getUTCFullYear()
  return `${dd}/${mm}/${yyyy}`
}

function fmtMoney(n, currency = 'USD') {
  const num = Number(n) || 0
  return `${num.toFixed(2)} ${currency}`
}

// Category emoji map for the folio detail rows. Falls back to "·" if
// no emoji is mapped (no hard fail). Mirrors what the hotelier UI uses.
const CATEGORY_EMOJI = {
  bar: '🍺', restaurant: '🍳', spa: '🧖', minibar: '🍷',
  laundry: '🧺', tour: '🗺️', transport: '🚐', phone: '📞',
  wifi: '📶', gift_shop: '🎁', late_checkout: '🕓', damage: '⚠️',
  cleaning: '🧹', package: '📦', other: '·',
}

// Section heading bar with brand-orange accent + title.
function drawSectionHeading(page, { x, y, w, text, fontBold }) {
  page.drawRectangle({ x, y: y - 18, width: 3, height: 14, color: ORANGE })
  page.drawText(text, { x: x + 10, y: y - 14, size: 11, font: fontBold, color: DEEP })
  page.drawRectangle({ x, y: y - 21, width: w, height: 0.5, color: rgb(0.85, 0.83, 0.80) })
  return y - 30
}

// Two-column money row: label on the left, amount on the right.
// Returns y - rowHeight for chaining.
function drawMoneyRow(page, { y, label, amount, currency, font, fontBold, bold, color = DEEP, indent = 0 }) {
  const lineFont = bold ? fontBold : font
  page.drawText(label, { x: MARGIN + indent, y, size: 10, font: lineFont, color })
  const txt = fmtMoney(amount, currency)
  // Right-align: position at MARGIN + contentW - text width
  const textWidth = lineFont.widthOfTextAtSize(txt, 10)
  page.drawText(txt, {
    x: A4.width - MARGIN - textWidth,
    y,
    size: 10, font: lineFont, color,
  })
  return y - 14
}

// ============================================================================
// Main entry — generateCheckoutBill
// ============================================================================
export async function generateCheckoutBill({
  booking,
  property,
  room,
  charges = [],
  vouchers = [],
  guestName,
}) {
  if (!booking || !property) {
    throw new Error('generateCheckoutBill: booking and property required')
  }

  const pdfDoc = await PDFDocument.create()
  pdfDoc.setTitle(`Bill ${booking.booking_ref || booking.id} — ${property.name}`)
  pdfDoc.setAuthor(property.name || 'STAYLO')
  pdfDoc.setCreator('STAYLO Dashboard')

  const font     = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const fontItalic = await pdfDoc.embedFont(StandardFonts.HelveticaOblique)

  const page = pdfDoc.addPage([A4.width, A4.height])
  const contentW = A4.width - 2 * MARGIN
  const currency = (booking.currency || property.currency || 'USD').toUpperCase()

  // ── Header band ─────────────────────────────────────────────
  page.drawRectangle({
    x: 0, y: A4.height - 80, width: A4.width, height: 80,
    color: DEEP,
  })
  page.drawText('INVOICE', {
    x: MARGIN, y: A4.height - 34, size: 22, font: fontBold,
    color: rgb(1, 1, 1),
  })
  page.drawText('Check-out bill', {
    x: MARGIN, y: A4.height - 54, size: 11, font,
    color: rgb(0.85, 0.86, 0.92),
  })
  if (booking.booking_ref) {
    page.drawText(`Ref · ${booking.booking_ref}`, {
      x: MARGIN, y: A4.height - 70, size: 9, font: fontItalic,
      color: rgb(0.65, 0.66, 0.75),
    })
  }
  // STAYLO mark top-right
  page.drawText('STAY', {
    x: A4.width - 90, y: A4.height - 34, size: 16, font: fontBold,
    color: rgb(1, 1, 1),
  })
  page.drawText('LO', {
    x: A4.width - 55, y: A4.height - 34, size: 16, font: fontBold,
    color: PINK,
  })
  page.drawText(new Date().toLocaleDateString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric',
  }), {
    x: A4.width - 130, y: A4.height - 54, size: 9, font,
    color: rgb(0.65, 0.66, 0.75),
  })

  let y = A4.height - 100

  // ── Property + guest block (two-col) ───────────────────────
  // Left: hotel address. Right: guest name + stay window.
  const halfW = (contentW - 12) / 2
  page.drawText('From', {
    x: MARGIN, y, size: 9, font: fontBold, color: GRAY,
  })
  page.drawText('Bill to', {
    x: MARGIN + halfW + 12, y, size: 9, font: fontBold, color: GRAY,
  })
  y -= 14
  page.drawText(t(property.name), { x: MARGIN, y, size: 12, font: fontBold, color: DEEP })
  page.drawText(t(guestName || booking.guest_name || 'Guest'), {
    x: MARGIN + halfW + 12, y, size: 12, font: fontBold, color: DEEP,
  })
  y -= 13
  if (property.address) page.drawText(t(property.address), { x: MARGIN, y, size: 9, font, color: GRAY })
  if (booking.guest_email) page.drawText(t(booking.guest_email), {
    x: MARGIN + halfW + 12, y, size: 9, font, color: GRAY,
  })
  y -= 12
  if (property.city || property.country) {
    page.drawText(t([property.city, property.country].filter(Boolean).join(', ')), {
      x: MARGIN, y, size: 9, font, color: GRAY,
    })
  }
  if (booking.guest_phone) page.drawText(t(booking.guest_phone), {
    x: MARGIN + halfW + 12, y, size: 9, font, color: GRAY,
  })
  y -= 18

  // ── Section 1: Stay summary ────────────────────────────────
  y = drawSectionHeading(page, {
    x: MARGIN, y, w: contentW,
    text: 'Stay summary', fontBold,
  })

  const nights = Math.max(
    1,
    Math.ceil((new Date(booking.check_out) - new Date(booking.check_in)) / 86400000)
  )
  page.drawText(`Check-in:   ${fmtDateISO(booking.check_in)}`,  { x: MARGIN,          y, size: 10, font, color: DEEP })
  page.drawText(`Check-out:  ${fmtDateISO(booking.check_out)}`, { x: MARGIN + 180,    y, size: 10, font, color: DEEP })
  page.drawText(`${nights} night${nights > 1 ? 's' : ''}`,      { x: MARGIN + 360,    y, size: 10, font: fontBold, color: ORANGE })
  y -= 14
  if (room?.name) {
    page.drawText(`Room: ${room.name}`, { x: MARGIN, y, size: 10, font, color: DEEP })
    if (room.bed_type) {
      page.drawText(`  ·  ${String(room.bed_type).replace(/_/g, ' ')} bed`, {
        x: MARGIN + 100, y, size: 10, font, color: GRAY,
      })
    }
    y -= 14
  }
  if (booking.adults || booking.guests) {
    const adults = booking.adults ?? booking.guests ?? 1
    const children = booking.children ?? 0
    page.drawText(`Guests: ${adults} adult${adults > 1 ? 's' : ''}${children > 0 ? ` + ${children} child${children > 1 ? 'ren' : ''}` : ''}`, {
      x: MARGIN, y, size: 10, font, color: DEEP,
    })
    y -= 14
  }
  y -= 6

  // ── Section 2: Room charge ─────────────────────────────────
  // booking.total_price is the agreed nightly rate × nights (or whatever
  // the booking engine settled on). We surface it as a single line.
  y = drawSectionHeading(page, { x: MARGIN, y, w: contentW, text: 'Room charge', fontBold })
  const roomTotal = Number(booking.total_price || 0)
  y = drawMoneyRow(page, {
    y,
    label: `${nights}× ${room?.name || 'Room'} @ ${fmtMoney(roomTotal / nights, currency)}`,
    amount: roomTotal,
    currency, font, fontBold,
  })
  y -= 6

  // ── Section 3: Extras (folio charges) ──────────────────────
  // We include unpaid AND paid lines on the printed bill — the guest's
  // copy should show everything that happened. Voucher-redemption $0
  // lines get their own section below.
  const moneyCharges = charges.filter(c => Number(c.amount) > 0)
  const voucherLines  = charges.filter(c => Number(c.amount) === 0 && /voucher/i.test(c.description || ''))

  if (moneyCharges.length > 0) {
    y = drawSectionHeading(page, { x: MARGIN, y, w: contentW, text: 'Extras', fontBold })
    for (const c of moneyCharges) {
      const emoji = CATEGORY_EMOJI[c.category] || '·'
      const label = `${emoji} ${c.description || c.category}${c.qty > 1 ? `   (${c.qty}× ${fmtMoney(c.unit_price, currency)})` : ''}`
      y = drawMoneyRow(page, {
        y,
        label,
        amount: Number(c.amount),
        currency, font, fontBold,
      })
    }
    y -= 6
  }

  // ── Section 4: Vouchers redeemed (audit, $0 each) ──────────
  // Pull from charges (the $0 mirror lines) so we don't double-count.
  // Falls back to vouchers with qty_consumed > 0 if no mirror lines
  // exist (older bookings before the auto-mirror behaviour).
  const redeemed = voucherLines.length > 0
    ? voucherLines
    : vouchers.filter(v => (v.qty_consumed || 0) > 0)
              .map(v => ({
                description: `🎁 ${v.label} (×${v.qty_consumed})`,
                amount: 0,
                category: 'package',
              }))
  if (redeemed.length > 0) {
    y = drawSectionHeading(page, { x: MARGIN, y, w: contentW, text: 'Vouchers redeemed (included)', fontBold })
    for (const c of redeemed) {
      const label = c.description || '🎁 Voucher'
      page.drawText(label.length > 60 ? label.slice(0, 60) + '…' : label, {
        x: MARGIN + 14, y, size: 10, font, color: LIBRE,
      })
      const incl = 'included'
      const w = font.widthOfTextAtSize(incl, 10)
      page.drawText(incl, {
        x: A4.width - MARGIN - w, y, size: 10, font: fontItalic, color: LIBRE,
      })
      y -= 14
    }
    y -= 6
  }

  // ── Section 5: Total ───────────────────────────────────────
  // Subtotal = room + paid charges + unpaid charges (everything money).
  // Discounts/promos can be a future line; for V1 we don't apply tax.
  const extrasTotal = moneyCharges.reduce((s, c) => s + Number(c.amount || 0), 0)
  const subtotal    = roomTotal + extrasTotal
  // Already-paid amount = paid charges + room (if booking.escrow_status =
  // 'released' meaning the platform already paid the hotel, the room is
  // settled). Keep it simple in V1: room=settled, paid charges=settled.
  const paidExtras  = moneyCharges.filter(c => c.paid).reduce((s, c) => s + Number(c.amount || 0), 0)
  const dueExtras   = moneyCharges.filter(c => !c.paid).reduce((s, c) => s + Number(c.amount || 0), 0)
  const balanceDue  = dueExtras

  // Sep line
  page.drawRectangle({ x: MARGIN, y, width: contentW, height: 0.7, color: DEEP })
  y -= 14

  y = drawMoneyRow(page, { y, label: 'Subtotal', amount: subtotal, currency, font, fontBold })
  y = drawMoneyRow(page, { y, label: 'Paid (already settled)', amount: -paidExtras, currency, font, fontBold, color: GRAY })

  // Big bold "Balance due" row
  page.drawRectangle({
    x: MARGIN - 4, y: y - 4, width: contentW + 8, height: 24,
    color: rgb(0.99, 0.94, 0.88),
  })
  y -= 4
  const balLabel = 'Balance due'
  page.drawText(balLabel, { x: MARGIN + 4, y: y - 8, size: 12, font: fontBold, color: ORANGE })
  const balText = fmtMoney(balanceDue, currency)
  const balW = fontBold.widthOfTextAtSize(balText, 14)
  page.drawText(balText, {
    x: A4.width - MARGIN - balW - 4,
    y: y - 9,
    size: 14, font: fontBold, color: ORANGE,
  })
  y -= 24

  // ── Footer ─────────────────────────────────────────────────
  const stamp = `Generated by STAYLO · ${new Date().toISOString().slice(0, 10)} · ref ${t(booking.id).slice(0, 8)}`
  page.drawText(stamp, {
    x: MARGIN, y: 24, size: 8, font: fontItalic, color: GRAY,
  })
  if (balanceDue > 0) {
    page.drawText('Please settle the balance at the front desk before departure. Thank you for staying with us!', {
      x: MARGIN, y: 38, size: 9, font: fontItalic, color: DEEP,
    })
  } else {
    page.drawText('Your account is fully settled. Thank you for staying with us!', {
      x: MARGIN, y: 38, size: 9, font: fontItalic, color: LIBRE,
    })
  }

  return await pdfDoc.save()
}


// ============================================================================
// Browser helper — trigger a download in one call.
// ============================================================================
export async function downloadCheckoutBill(args) {
  const bytes = await generateCheckoutBill(args)
  const blob = new Blob([bytes], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  const safeProp = (args.property?.name || 'property').replace(/[^a-z0-9-_]+/gi, '_')
  const safeRef  = (args.booking?.booking_ref || args.booking?.id || 'bill').toString().slice(0, 12)
  a.download = `Bill_${safeProp}_${safeRef}.pdf`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 1000)
  return bytes
}
