// ============================================================================
// TM30 — Notification of Accommodation (Thailand Immigration Bureau)
// ============================================================================
// Generates a programmatic PDF of the TM30 form pre-filled from STAYLO data
// (booking + guest profile + property). The hotelier downloads it, prints
// or uploads to https://extranet.immigration.go.th within 24h of the
// guest's arrival as required by Section 38 of the Thai Immigration Act.
//
// Why programmatic and not a fillable template overlay?
//   The official IB PDF has changed format 3 times since 2020 and the
//   fillable fields are unreliable across renderers (some readers ignore
//   the AcroForm). Generating from scratch with pdf-lib gives us:
//     · Same visual output everywhere (no font substitution drift)
//     · No dependency on a specific template version
//     · Clean source of truth for batch generation (S2f-batch)
//   Once the IB publishes a stable fillable PDF, swap this for
//   pdf-lib's `PDFDocument.load(template).getForm()` flow without
//   touching the caller — the function signature is stable.
//
// Legal disclaimer
//   STAYLO assists the hotelier in PRE-FILLING the TM30. The hotelier
//   remains legally responsible for submission to the IB and for the
//   accuracy of data. The PDF is marked "Generated by STAYLO" in the
//   footer for traceability.
//
// Usage
//   import { generateTM30PDF } from '../../lib/tm30'
//   const bytes = await generateTM30PDF({ booking, property, guests })
//   // bytes is a Uint8Array — wrap in Blob to download or upload.
// ============================================================================
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

// STAYLO brand colours, kept consistent with the rest of the dashboard.
const DEEP    = rgb(0.10, 0.12, 0.18) // #1A1F2E
const ORANGE  = rgb(1.00, 0.42, 0.00) // #FF6B00
const PINK    = rgb(1.00, 0.24, 0.71) // #FF3CB4
const ELECTRIC = rgb(0.42, 0.36, 0.91) // #6C5CE7
const GRAY    = rgb(0.45, 0.45, 0.48)
const SOFT_BG = rgb(0.97, 0.96, 0.94) // #F8F6F0

const A4 = { width: 595.28, height: 841.89 }
const MARGIN = 40
const COL_GAP = 14

// Helper — safe text, never crashes if a field is undefined/null.
const t = v => (v == null ? '' : String(v))

// Format date helpers — TM30 expects DD/MM/YYYY style.
function fmtDateDDMMYYYY(iso) {
  if (!iso) return ''
  const d = new Date(typeof iso === 'string' && iso.length === 10 ? iso + 'T00:00:00Z' : iso)
  if (isNaN(d)) return t(iso)
  const dd = String(d.getUTCDate()).padStart(2, '0')
  const mm = String(d.getUTCMonth() + 1).padStart(2, '0')
  const yyyy = d.getUTCFullYear()
  return `${dd}/${mm}/${yyyy}`
}

// Wrapper that draws a labeled field cell (label on top, value below in a
// light box). Returns the y-offset of the next available drawing point.
function drawFieldCell(page, { x, y, w, h, label, value, font, fontBold }) {
  // Label
  page.drawText(label, {
    x: x + 4, y: y - 9, size: 7, font: fontBold, color: GRAY,
  })
  // Value box
  page.drawRectangle({
    x, y: y - h, width: w, height: h - 12,
    borderColor: rgb(0.85, 0.83, 0.80), borderWidth: 0.6,
    color: rgb(1, 1, 1),
  })
  // Value text — clip to box width with naive truncation.
  const txt = t(value)
  const maxChars = Math.floor((w - 8) / 5.2) // ~5px per char at size 10
  const shown = txt.length > maxChars ? txt.slice(0, maxChars - 1) + '…' : txt
  page.drawText(shown, {
    x: x + 4, y: y - h + 6, size: 10, font, color: DEEP,
  })
  return y - h - 6
}

// Draws a section heading bar with brand-orange accent.
function drawSectionHeading(page, { x, y, w, text, fontBold }) {
  page.drawRectangle({
    x, y: y - 18, width: 3, height: 14,
    color: ORANGE,
  })
  page.drawText(text, {
    x: x + 10, y: y - 14, size: 10, font: fontBold, color: DEEP,
  })
  page.drawRectangle({
    x, y: y - 21, width: w, height: 0.5, color: rgb(0.85, 0.83, 0.80),
  })
  return y - 30
}

// ============================================================================
// Main entry point
// ============================================================================
export async function generateTM30PDF({ booking, property, guests }) {
  if (!booking || !property) {
    throw new Error('generateTM30PDF: booking and property are required')
  }
  // Normalise to an array — single-guest bookings still go through here.
  const guestList = Array.isArray(guests) && guests.length > 0
    ? guests
    : [{
        first_name: (booking.guest_name || '').split(' ')[0] || '',
        last_name:  (booking.guest_name || '').split(' ').slice(1).join(' '),
        nationality: '',
        passport_number: '',
        passport_expires_at: null,
        date_of_birth: null,
        sex: null,
      }]

  const pdfDoc = await PDFDocument.create()
  pdfDoc.setTitle(`TM30 — ${property.name} — ${booking.check_in}`)
  pdfDoc.setAuthor('STAYLO')
  pdfDoc.setSubject('Notification of Accommodation (Thai Immigration Form TM.30)')
  pdfDoc.setCreator('STAYLO Dashboard')
  pdfDoc.setProducer('pdf-lib')

  const font     = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const fontItalic = await pdfDoc.embedFont(StandardFonts.HelveticaOblique)

  const page = pdfDoc.addPage([A4.width, A4.height])

  // ── Header band (STAYLO brand strip) ──
  page.drawRectangle({
    x: 0, y: A4.height - 70, width: A4.width, height: 70,
    color: DEEP,
  })
  // Title in white
  page.drawText('ตม.30  •  TM.30', {
    x: MARGIN, y: A4.height - 32, size: 18, font: fontBold,
    color: rgb(1, 1, 1),
  })
  page.drawText('Notification of Accommodation', {
    x: MARGIN, y: A4.height - 50, size: 11, font,
    color: rgb(0.85, 0.86, 0.92),
  })
  page.drawText('Per Section 38 — Immigration Act B.E. 2522', {
    x: MARGIN, y: A4.height - 62, size: 8, font: fontItalic,
    color: rgb(0.65, 0.66, 0.75),
  })
  // STAYLO mark — bottom right of header band
  page.drawText('STAY', {
    x: A4.width - 80, y: A4.height - 35, size: 14, font: fontBold,
    color: rgb(1, 1, 1),
  })
  page.drawText('LO', {
    x: A4.width - 50, y: A4.height - 35, size: 14, font: fontBold,
    color: PINK,
  })
  page.drawText('Generated automatically', {
    x: A4.width - 130, y: A4.height - 50, size: 7, font,
    color: rgb(0.65, 0.66, 0.75),
  })

  let y = A4.height - 90

  // ── Property block ──
  const contentW = A4.width - 2 * MARGIN
  y = drawSectionHeading(page, {
    x: MARGIN, y, w: contentW,
    text: 'A. Accommodation provider', fontBold,
  })

  // Property name (full width)
  y = drawFieldCell(page, {
    x: MARGIN, y, w: contentW, h: 28,
    label: 'PROPERTY NAME · ชื่อสถานที่',
    value: property.name,
    font, fontBold,
  })

  // Address: city + country side-by-side, then full address line
  const halfW = (contentW - COL_GAP) / 2
  const before = y
  drawFieldCell(page, {
    x: MARGIN, y, w: halfW, h: 28,
    label: 'CITY · จังหวัด',
    value: property.city,
    font, fontBold,
  })
  y = drawFieldCell(page, {
    x: MARGIN + halfW + COL_GAP, y, w: halfW, h: 28,
    label: 'COUNTRY · ประเทศ',
    value: property.country,
    font, fontBold,
  })

  if (property.address) {
    y = drawFieldCell(page, {
      x: MARGIN, y, w: contentW, h: 28,
      label: 'ADDRESS · ที่อยู่',
      value: property.address,
      font, fontBold,
    })
  }

  // Owner / manager
  y = drawFieldCell(page, {
    x: MARGIN, y, w: contentW, h: 28,
    label: 'MANAGER · ชื่อผู้จัดการ',
    value: property.owner_name || property.contact_name || '',
    font, fontBold,
  })

  // ── Stay block ──
  y -= 8
  y = drawSectionHeading(page, {
    x: MARGIN, y, w: contentW,
    text: 'B. Stay details', fontBold,
  })

  drawFieldCell(page, {
    x: MARGIN, y, w: halfW, h: 28,
    label: 'CHECK-IN DATE · วันเข้าพัก',
    value: fmtDateDDMMYYYY(booking.check_in),
    font, fontBold,
  })
  y = drawFieldCell(page, {
    x: MARGIN + halfW + COL_GAP, y, w: halfW, h: 28,
    label: 'CHECK-OUT DATE · วันออก',
    value: fmtDateDDMMYYYY(booking.check_out),
    font, fontBold,
  })

  // Room number / type
  drawFieldCell(page, {
    x: MARGIN, y, w: halfW, h: 28,
    label: 'ROOM · ห้องพัก',
    value: booking.room_name || booking.room_id || '',
    font, fontBold,
  })
  y = drawFieldCell(page, {
    x: MARGIN + halfW + COL_GAP, y, w: halfW, h: 28,
    label: '# GUESTS · จำนวน',
    value: t(guestList.length),
    font, fontBold,
  })

  // ── Guest block (one per traveler) ──
  y -= 8
  y = drawSectionHeading(page, {
    x: MARGIN, y, w: contentW,
    text: `C. Foreign national${guestList.length > 1 ? 's' : ''} (${guestList.length})`, fontBold,
  })

  for (let i = 0; i < guestList.length; i++) {
    const g = guestList[i]
    // Page break if we get too low — TM30 supports continuation page.
    if (y < 180) {
      const newPage = pdfDoc.addPage([A4.width, A4.height])
      // Mini header on continuation page
      newPage.drawText(`TM.30 (continued) — ${property.name}`, {
        x: MARGIN, y: A4.height - 30, size: 10, font: fontBold, color: DEEP,
      })
      // Reset y and switch page reference for subsequent draws.
      // Note: rest of function uses `page` directly — we keep adding to the
      // same page reference. Simpler approach: warn user with a footer note
      // for now, defer multi-page to a follow-up.
      newPage.drawText('Additional guests — please attach separately for now.', {
        x: MARGIN, y: A4.height - 50, size: 9, font: fontItalic, color: ORANGE,
      })
      break
    }
    // Subheading per guest
    page.drawRectangle({
      x: MARGIN, y: y - 16, width: contentW, height: 16,
      color: SOFT_BG,
    })
    page.drawText(`Guest ${i + 1}`, {
      x: MARGIN + 6, y: y - 12, size: 8, font: fontBold, color: ELECTRIC,
    })
    const nameDisp = `${t(g.first_name)} ${t(g.last_name)}`.trim()
    page.drawText(nameDisp || '—', {
      x: MARGIN + 60, y: y - 12, size: 9, font: fontBold, color: DEEP,
    })
    y -= 22

    // First name / last name
    drawFieldCell(page, {
      x: MARGIN, y, w: halfW, h: 26,
      label: 'FAMILY NAME · นามสกุล',
      value: g.last_name,
      font, fontBold,
    })
    y = drawFieldCell(page, {
      x: MARGIN + halfW + COL_GAP, y, w: halfW, h: 26,
      label: 'GIVEN NAME · ชื่อ',
      value: g.first_name,
      font, fontBold,
    })

    // Nationality + DOB + Sex (three-column row)
    const triW = (contentW - 2 * COL_GAP) / 3
    drawFieldCell(page, {
      x: MARGIN, y, w: triW, h: 26,
      label: 'NATIONALITY · สัญชาติ',
      value: g.nationality,
      font, fontBold,
    })
    drawFieldCell(page, {
      x: MARGIN + triW + COL_GAP, y, w: triW, h: 26,
      label: 'DATE OF BIRTH · วันเกิด',
      value: fmtDateDDMMYYYY(g.date_of_birth),
      font, fontBold,
    })
    y = drawFieldCell(page, {
      x: MARGIN + 2 * (triW + COL_GAP), y, w: triW, h: 26,
      label: 'SEX · เพศ',
      value: g.sex || '',
      font, fontBold,
    })

    // Passport number + expiry
    drawFieldCell(page, {
      x: MARGIN, y, w: halfW, h: 26,
      label: 'PASSPORT NO. · หมายเลขหนังสือเดินทาง',
      value: g.passport_number,
      font, fontBold,
    })
    y = drawFieldCell(page, {
      x: MARGIN + halfW + COL_GAP, y, w: halfW, h: 26,
      label: 'EXPIRES · วันหมดอายุ',
      value: fmtDateDDMMYYYY(g.passport_expires_at),
      font, fontBold,
    })

    y -= 4 // breathing room between guests
  }

  // ── Footer — declaration + signatures ──
  // Position at fixed bottom of page so multiple guests don't push it.
  const footerY = 130
  page.drawRectangle({
    x: MARGIN, y: footerY - 80, width: contentW, height: 0.5,
    color: rgb(0.85, 0.83, 0.80),
  })
  page.drawText('Declaration', {
    x: MARGIN, y: footerY - 14, size: 10, font: fontBold, color: DEEP,
  })
  page.drawText(
    'I certify that the information above is accurate to the best of my knowledge,',
    { x: MARGIN, y: footerY - 30, size: 9, font, color: DEEP }
  )
  page.drawText(
    'and that this notification is submitted within 24 hours of the guest\'s arrival.',
    { x: MARGIN, y: footerY - 42, size: 9, font, color: DEEP }
  )

  // Signature lines
  page.drawLine({
    start: { x: MARGIN, y: footerY - 80 },
    end:   { x: MARGIN + 200, y: footerY - 80 },
    thickness: 0.7, color: DEEP,
  })
  page.drawText('Signature · Manager', {
    x: MARGIN, y: footerY - 92, size: 7, font: fontBold, color: GRAY,
  })

  page.drawLine({
    start: { x: A4.width - MARGIN - 200, y: footerY - 80 },
    end:   { x: A4.width - MARGIN, y: footerY - 80 },
    thickness: 0.7, color: DEEP,
  })
  page.drawText('Date submitted (DD/MM/YYYY)', {
    x: A4.width - MARGIN - 200, y: footerY - 92, size: 7, font: fontBold, color: GRAY,
  })

  // Generation stamp — bottom of page
  const stamp = `Generated by STAYLO · ${new Date().toISOString().slice(0, 10)} · ref ${t(booking.id).slice(0, 8)}`
  page.drawText(stamp, {
    x: MARGIN, y: 16, size: 7, font: fontItalic, color: GRAY,
  })
  page.drawText('Upload at https://extranet.immigration.go.th within 24h of arrival.', {
    x: MARGIN, y: 28, size: 7, font: fontItalic, color: ORANGE,
  })

  return await pdfDoc.save()
}

// ============================================================================
// Helper — trigger a browser download of the PDF.
// ============================================================================
export async function downloadTM30({ booking, property, guests, filename }) {
  const bytes = await generateTM30PDF({ booking, property, guests })
  const blob = new Blob([bytes], { type: 'application/pdf' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  const safeName = (property?.name || 'property').replace(/[^a-z0-9-_]+/gi, '_')
  const safeDate = (booking?.check_in || new Date().toISOString().slice(0, 10))
  a.download = filename || `TM30_${safeName}_${safeDate}.pdf`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  // Defer revoke so the click has had time to start the download.
  setTimeout(() => URL.revokeObjectURL(url), 1000)
  return bytes
}
