#!/usr/bin/env node
/**
 * Batch 2 — heavyweight namespaces (dashboard, manage, booking, checkout, survey).
 * Same conventions as _translate_batch.cjs.
 */
const fs = require('fs'); const path = require('path');
const ROOT = path.join(__dirname, '..');

const T = {
  dashboard: {
    cta_become_host: { fr: 'Inscrire une propriété', th: 'ลงทะเบียนทรัพย์สิน' },
    cta_become_host_sub: { fr: 'Devenez hôtelier sur STAYLO — gratuit, 15 minutes.', th: 'เป็นเจ้าของโรงแรมบน STAYLO — ฟรี 15 นาที' },
    section_team_tools: { fr: 'Outils équipe', th: 'เครื่องมือทีม' },
    nav_messenger: { fr: 'Staff Messenger', th: 'Staff Messenger' },
    nav_guest_app: { fr: 'App Guest', th: 'App Guest' },
    back_to_site: { fr: 'Retour à Staylo', th: 'กลับสู่ Staylo' },
    kit_title: { fr: 'Mon Welcome Kit', th: 'Welcome Kit ของฉัน' },
    kit_subtitle: { fr: 'Vos supports personnalisés pour faire croître le réseau Staylo', th: 'สื่อปรับแต่งของคุณเพื่อขยายเครือข่าย Staylo' },
    kit_qr_title: { fr: 'Votre QR code unique', th: 'QR code เฉพาะของคุณ' },
    kit_qr_desc: { fr: 'Ce QR code est imprimé sur tous vos supports kit. Chaque scan est tracé sur votre compte.', th: 'QR code นี้พิมพ์บนสื่อ kit ทั้งหมด ทุกการสแกนถูกบันทึกในบัญชีของคุณ' },
    kit_first_free: { fr: 'Votre premier kit est GRATUIT', th: 'ชุดแรกของคุณฟรี' },
    kit_first_desc: { fr: 'En tant que Founding Partner, votre Welcome Kit personnalisé vous est expédié gratuitement. Les recharges sont disponibles au prix coûtant via Print-on-Demand.', th: 'ในฐานะ Founding Partner ชุด Welcome Kit ที่ปรับแต่งสำหรับคุณส่งให้ฟรี ชุดทดแทนหาได้ที่ราคาทุนผ่าน Print-on-Demand' },
    kit_items_title: { fr: 'Contenu & recharges du kit', th: 'เนื้อหาและการเติมชุดอุปกรณ์' },
    kit_items: { fr: 'élément(s)', th: 'รายการ' },
    kit_pod: { fr: 'Print-on-Demand — expédition locale', th: 'Print-on-Demand — จัดส่งภายในประเทศ' },
    kit_order: { fr: 'Commander des recharges', th: 'สั่งซื้อชุดทดแทน' },
    kit_ordered: { fr: 'Commande reçue !', th: 'รับคำสั่งซื้อแล้ว!' },
    kit_ordered_desc: { fr: 'Votre kit de recharge sera imprimé et expédié localement. Vous recevrez un numéro de suivi par email.', th: 'ชุดทดแทนจะถูกพิมพ์และส่งภายในประเทศ คุณจะได้รับหมายเลขติดตามทางอีเมล' },
    kit_new_order: { fr: 'Passer une autre commande', th: 'สั่งซื้ออีกครั้ง' },
    my_properties: { fr: 'Mes propriétés', th: 'ทรัพย์สินของฉัน' },
    properties_count_label: { fr: '{{count}} propriétés enregistrées', th: 'ลงทะเบียนแล้ว {{count}} ทรัพย์สิน' },
    no_properties_title: { fr: 'Aucune propriété pour le moment', th: 'ยังไม่มีทรัพย์สิน' },
    no_properties_detail: { fr: 'Enregistrez votre première propriété pour commencer. Cela ne prend que quelques minutes.', th: 'ลงทะเบียนทรัพย์สินแรกเพื่อเริ่มต้น ใช้เวลาเพียงไม่กี่นาที' },
    avg_rate: { fr: '~${{rate}}/nuit', th: '~${{rate}}/คืน' },
    manage: { fr: 'Gérer', th: 'จัดการ' },
    my_referrals: { fr: 'Mes parrainages', th: 'การแนะนำของฉัน' },
    referrals_subtitle: { fr: 'Suivez vos parrainages et faites grandir la communauté', th: 'ติดตามการแนะนำของคุณและขยายชุมชน' },
    total_referred: { fr: 'Total parrainés', th: 'แนะนำทั้งหมด' },
    hotels_referred: { fr: 'Hôtels parrainés', th: 'โรงแรมที่แนะนำ' },
    ambassadors_referred: { fr: 'Ambassadors parrainés', th: 'Ambassador ที่แนะนำ' },
    your_referral_link: { fr: 'Votre lien de parrainage', th: 'ลิงก์แนะนำของคุณ' },
    referred_users: { fr: 'Utilisateurs parrainés', th: 'ผู้ใช้ที่แนะนำ' },
    no_referrals_yet: { fr: 'Aucun parrainage pour le moment. Partagez votre lien pour commencer à faire croître la communauté !', th: 'ยังไม่มีการแนะนำ แชร์ลิงก์ของคุณเพื่อเริ่มขยายชุมชน!' },
    ref_name: { fr: 'Nom', th: 'ชื่อ' },
    ref_email: { fr: 'Email', th: 'อีเมล' },
    ref_type: { fr: 'Type', th: 'ประเภท' },
    ref_date: { fr: "Date d'adhésion", th: 'วันที่เข้าร่วม' },
    ref_unknown: { fr: 'Inconnu', th: 'ไม่ทราบ' },
    ref_type_hotel: { fr: 'Hôtel', th: 'โรงแรม' },
    my_shares: { fr: 'Mes parts', th: 'หุ้นของฉัน' },
    shares_subtitle: { fr: 'Votre statut Founding Partner et détails de votre investissement', th: 'สถานะ Founding Partner และรายละเอียดการลงทุนของคุณ' },
    partnership_progress: { fr: 'Progression du partenariat', th: 'ความคืบหน้าของการเป็นพันธมิตร' },
    shares_held: { fr: 'Parts détenues', th: 'หุ้นที่ถือ' },
    total_value: { fr: 'Valeur totale', th: 'มูลค่ารวม' },
    est_savings_year: { fr: "Économies annuelles est.", th: 'ประหยัดต่อปี (โดยประมาณ)' },
    share_details: { fr: 'Détails des parts', th: 'รายละเอียดหุ้น' },
    price_per_share: { fr: 'Prix par part', th: 'ราคาต่อหุ้น' },
    max_per_property: { fr: 'Max par propriété', th: 'สูงสุดต่อทรัพย์สิน' },
    total_available_alpha: { fr: 'Total disponible (Alpha)', th: 'รวมที่มี (Alpha)' },
    voting_rule: { fr: 'Règle de vote', th: 'กฎการลงคะแนน' },
    one_property_one_vote: { fr: '1 propriété = 1 vote', th: '1 ทรัพย์สิน = 1 เสียง' },
    share_transfer: { fr: 'Transfert de parts', th: 'การโอนหุ้น' },
    freely_transferable: { fr: 'Librement transférables', th: 'โอนได้อย่างอิสระ' },
    loi_cta_text: { fr: 'Prêt à devenir Founding Partner ? Commencez par signer la lettre d\'intention.', th: 'พร้อมจะเป็น Founding Partner หรือยัง? เริ่มจากการลงนาม Letter of Intent' },
    call_confirmed_title: { fr: 'On vous contacte !', th: 'เราจะติดต่อคุณ!' },
    call_confirmed_desc: { fr: "Un membre de l'équipe Staylo vous contactera par", th: 'สมาชิกทีม Staylo จะติดต่อคุณทาง' },
    call_asap_note: { fr: 'Nous essaierons de vous joindre dans les 30 prochaines minutes !', th: 'เราจะพยายามติดต่อคุณภายใน 30 นาทีถัดไป!' },
    call_time_note: { fr: 'Heure préférée :', th: 'เวลาที่สะดวก:' },
    call_title: { fr: 'Bienvenue ! Rencontrons-nous.', th: 'ยินดีต้อนรับ! มาคุยกันเถอะ' },
    call_subtitle: { fr: 'Pour finaliser votre inscription, on aimerait un petit welcome call. Comment préférez-vous être contacté ?', th: 'เพื่อสรุปการลงทะเบียน เราอยากมี welcome call สั้นๆ คุณอยากให้ติดต่อทางไหน?' },
    call_email_label: { fr: "Votre email pour l'invitation", th: 'อีเมลของคุณสำหรับคำเชิญ' },
    call_number_label: { fr: 'Votre numéro de téléphone ou ID', th: 'เบอร์โทรศัพท์หรือ ID' },
    call_time_label: { fr: 'Heure préférée', th: 'เวลาที่สะดวก' },
    call_time_placeholder: { fr: 'ex. 14h, matin, après-midi…', th: 'เช่น 14:00, ตอนเช้า, ตอนบ่าย…' },
    call_submit: { fr: 'Demander un appel', th: 'ขอการโทร' },
    stat_properties: { fr: 'Mes propriétés', th: 'ทรัพย์สินของฉัน' },
    stat_hotels_referred: { fr: 'Hôtels parrainés', th: 'โรงแรมที่แนะนำ' },
    stat_referred_hoteliers: { fr: "Hôteliers que j'ai parrainés", th: 'เจ้าของโรงแรมที่ฉันแนะนำ' },
    stat_monthly_revenue: { fr: 'Revenu ce mois', th: 'รายได้เดือนนี้' },
    qr_desc_short: { fr: "Imprimez-le, montrez-le — toute personne qui scanne vous est rattachée à vie.", th: 'พิมพ์ออกมา แสดงไว้ — ใครที่สแกนจะเชื่อมกับคุณตลอดไป' },
    calc_hint: { fr: "Touchez n'importe quel chiffre pour le modifier et voir l'économie se mettre à jour en direct.", th: 'แตะตัวเลขใดก็ได้เพื่อแก้ไขและดูการประหยัดอัปเดตทันที' },
    calc_reset: { fr: 'Revenir à mes données', th: 'รีเซ็ตกลับข้อมูลของฉัน' },
    calc_rooms: { fr: 'Chambres totales', th: 'ห้องทั้งหมด' },
    calc_rate: { fr: 'Tarif moyen / nuit', th: 'ราคาเฉลี่ยต่อคืน' },
    calc_occupancy: { fr: "Taux d'occupation moyen", th: 'อัตราการเข้าพักเฉลี่ย' },
    calc_annual_revenue: { fr: 'Revenu annuel estimé des réservations', th: 'รายได้จากการจองรายปีโดยประมาณ' },
    calc_ota_commission: { fr: 'Commission OTA (~17%)', th: 'ค่าคอมมิชชั่น OTA (~17%)' },
    calc_staylo_commission: { fr: 'Commission Staylo (10%)', th: 'ค่าคอมมิชชั่น Staylo (10%)' },
    calc_you_save: { fr: 'Vous économisez', th: 'คุณประหยัด' },
    calc_explanation: { fr: 'Différence entre 17% OTA et 10% Staylo sur vos réservations estimées', th: 'ความต่างระหว่าง OTA 17% กับ Staylo 10% บนการจองโดยประมาณ' },
  },

  manage: {
    packages_title: { fr: 'Packages', th: 'แพ็คเกจ' },
    packages_sub: { fr: 'Créez des bundles que les clients peuvent ajouter à la réservation — lune de miel, wellness, retraite, plongée…', th: 'สร้างแพ็คเกจที่แขกสามารถเพิ่มขณะจอง — ฮันนีมูน เวลเนส รีทรีต ดำน้ำ…' },
    add_package: { fr: 'Ajouter un package', th: 'เพิ่มแพ็คเกจ' },
    no_packages: { fr: 'Aucun package pour le moment. Cliquez sur "Ajouter un package" pour créer le premier.', th: 'ยังไม่มีแพ็คเกจ คลิก "เพิ่มแพ็คเกจ" เพื่อสร้างแพ็คเกจแรก' },
    team_title: { fr: 'Équipe & permissions', th: 'ทีมและสิทธิ์' },
    team_subtitle: { fr: 'Ajoutez du staff ou des co-managers pour aider à gérer cette propriété. Ils doivent avoir un compte STAYLO.', th: 'เพิ่มพนักงานหรือผู้จัดการร่วมเพื่อช่วยจัดการทรัพย์สิน พวกเขาต้องมีบัญชี STAYLO ก่อน' },
    settings_title: { fr: 'Paramètres de la propriété', th: 'ตั้งค่าทรัพย์สิน' },
    settings_subtitle: { fr: 'Infos générales de la propriété susceptibles de changer dans le temps. Le bouton Enregistrer commit tout en une fois.', th: 'ข้อมูลทั่วไปของทรัพย์สินที่อาจเปลี่ยนแปลงตามเวลา ปุ่มบันทึกจะส่งทุกอย่างพร้อมกัน' },
    locked_title: { fr: 'Paramètres de la propriété verrouillés', th: 'การตั้งค่าทรัพย์สินถูกล็อค' },
    locked_desc: { fr: 'Votre propriété a été vérifiée par STAYLO. Les infos légales (nom, adresse, contact, politiques) sont en lecture seule. ', th: 'ทรัพย์สินได้รับการยืนยันจาก STAYLO แล้ว ข้อมูลทางกฎหมาย (ชื่อ ที่อยู่ ติดต่อ นโยบาย) อ่านได้อย่างเดียว' },
    property_name: { fr: 'Nom de la propriété', th: 'ชื่อทรัพย์สิน' },
    min_age: { fr: 'Âge minimum', th: 'อายุขั้นต่ำ' },
    locked_button: { fr: 'Verrouillé — contactez admin', th: 'ถูกล็อค — ติดต่อแอดมิน' },
    saving: { fr: 'Enregistrement…', th: 'กำลังบันทึก…' },
    videos_title: { fr: 'Vidéos', th: 'วิดีโอ' },
    videos_subtitle: { fr: "Jusqu'à 2 vidéos courtes. La première s'affiche en hero sur votre page propriété. Gardez-les sous 60 sec pour le meilleur engagement.", th: 'สูงสุด 2 วิดีโอสั้นๆ วิดีโอแรกจะแสดงเป็น hero บนหน้าทรัพย์สิน ทำให้สั้นกว่า 60 วินาทีเพื่อ engagement ดีที่สุด' },
    uploading: { fr: 'Téléversement', th: 'กำลังอัพโหลด' },
    upload_videos: { fr: 'Téléverser une vidéo', th: 'อัพโหลดวิดีโอ' },
    no_videos_title: { fr: 'Aucune vidéo pour le moment', th: 'ยังไม่มีวิดีโอ' },
    no_videos_desc: { fr: "Les propriétés avec vidéo reçoivent jusqu'à 80% de demandes de réservation en plus. Montrez vos chambres, espaces communs, et l'ambiance en un clip court.", th: 'ทรัพย์สินที่มีวิดีโอได้รับคำขอจองเพิ่มขึ้นถึง 80% โชว์ห้อง พื้นที่ส่วนกลาง และบรรยากาศในคลิปสั้นๆ' },
    videos_count: { fr: 'vidéos', th: 'วิดีโอ' },
    photos_title: { fr: 'Photos', th: 'รูปภาพ' },
    photos_subtitle: { fr: 'La première photo est la couverture affichée dans les résultats de recherche. Drag-to-reorder à venir.', th: 'รูปภาพแรกเป็นปกที่แสดงในผลการค้นหา ลากเพื่อจัดลำดับเร็วๆ นี้' },
    upload_photos: { fr: 'Téléverser des photos', th: 'อัพโหลดรูปภาพ' },
    no_photos_title: { fr: 'Aucune photo pour le moment', th: 'ยังไม่มีรูปภาพ' },
    no_photos_desc: { fr: 'Les propriétés sans photo ne peuvent pas être publiées. Téléversez au moins 3 images haute qualité de vos chambres, espaces communs, et vues.', th: 'ทรัพย์สินที่ไม่มีรูปไม่สามารถเปิดให้บริการได้ อัพโหลดรูปคุณภาพสูงอย่างน้อย 3 รูป' },
    photos_count: { fr: 'photos', th: 'รูปภาพ' },
    photos_warning: { fr: "Ajoutez au moins 3 photos avant la publication", th: 'เพิ่มรูปอย่างน้อย 3 รูปก่อนเปิดให้บริการ' },
    copy_from: { fr: 'Copier depuis une chambre existante', th: 'คัดลอกจากห้องที่มีอยู่' },
    copy_from_hint: { fr: 'optionnel, pré-remplit tout', th: 'ไม่บังคับ จะกรอกข้อมูลให้ทั้งหมด' },
    copy_from_none: { fr: 'Démarrer vide', th: 'เริ่มจากศูนย์' },
    pricing_unit: { fr: 'Modèle de tarification', th: 'รูปแบบการตั้งราคา' },
    people_per_bed: { fr: 'Personnes par lit', th: 'คนต่อเตียง' },
    price_default_hint: { fr: "C'est ce que paie le client. Vous pouvez le modifier par jour dans l'onglet Disponibilité.", th: 'นี่คือสิ่งที่แขกจ่าย คุณสามารถปรับเปลี่ยนรายวันได้ในแท็บความพร้อมใช้งาน' },
    net_received: { fr: 'Net que vous recevez', th: 'จำนวนสุทธิที่คุณได้รับ' },
    after_commission: { fr: 'après 10% de commission STAYLO', th: 'หลังหักค่าคอมมิชชั่น STAYLO 10%' },
    night: { fr: 'nuit', th: 'คืน' },
    communicating_rooms: { fr: 'Chambres communicantes disponibles', th: 'มีห้องสื่อสารกันได้' },
    communicating_rooms_hint: { fr: 'Au moins une paire de ce type de chambre est reliée par une porte interne', th: 'อย่างน้อยห้องคู่นี้มีประตูภายในเชื่อม' },
    communicating_with: { fr: 'Connecté avec quel type de chambre ?', th: 'เชื่อมกับห้องประเภทใด?' },
    extra_bed_offer: { fr: "Proposer des lits d'appoint pour enfants", th: 'เสนอเตียงเสริมสำหรับเด็ก' },
    extra_bed_hint: { fr: "Lit pliant facturé par nuit, enfants uniquement", th: 'เตียงพับคิดเป็นรายคืน เฉพาะเด็ก' },
    extra_bed_max_qty: { fr: 'Max de lits d\'appoint', th: 'จำนวนเตียงเสริมสูงสุด' },
    extra_bed_price: { fr: 'Prix/nuit (USD)', th: 'ราคา/คืน (USD)' },
    extra_bed_max_age: { fr: "Âge max de l'enfant", th: 'อายุสูงสุดของเด็ก' },
    extra_bed_adults: { fr: "Autoriser aussi les adultes sur le lit d'appoint", th: 'อนุญาตให้ผู้ใหญ่ใช้เตียงเสริมด้วย' },
    extra_bed_adults_hint: { fr: 'Pour des amis de dernière minute, OU un accompagnant d\'un client à mobilité réduite (aidant, accompagnant). Quand coché, la limite d\'âge devient informative.', th: 'สำหรับเพื่อนนาทีสุดท้าย หรือผู้ดูแลแขกที่มีการเคลื่อนไหวจำกัด เมื่อเลือก ขีดจำกัดอายุข้างต้นจะเป็นข้อมูล' },
    unit_numbers_title: { fr: 'Numéros physiques des unités', th: 'หมายเลขห้องจริง' },
    unit_numbers_hint: { fr: 'Optionnel. Les réceptionnistes choisissent depuis cette liste lors des attributions.', th: 'ไม่บังคับ พนักงานต้อนรับเลือกจากรายการนี้เมื่อจัดสรร' },
    unit_numbers_desc: { fr: 'Collez tous les numéros séparés par virgules ou retours à la ligne. ex. t.03, t.04, t.12, t.32 — pour un type Junior Suite avec quantité 4.', th: 'วางหมายเลขห้องคั่นด้วยจุลภาคหรือขึ้นบรรทัดใหม่ เช่น t.03, t.04, t.12, t.32 — สำหรับประเภท Junior Suite จำนวน 4 ห้อง' },
    long_stay_title: { fr: 'Tarifs longs séjours', th: 'อัตราพักระยะยาว' },
    long_stay_hint: { fr: 'Optionnel. Attrape les digital nomads + voyageurs mensuels.', th: 'ไม่บังคับ ดึงดูด digital nomad + นักเดินทางรายเดือน' },
    long_stay_desc: { fr: 'Définissez un tarif mensuel pour les séjours de ≥ N nuits. STAYLO applique automatiquement le meilleur de (journalier × nuits) vs (tarif_mensuel × nuits / 30) — les clients en long séjour paient moins, vous remplissez la chambre.', th: 'ตั้งอัตรารายเดือนสำหรับพัก ≥ N คืน STAYLO เลือกอัตราที่ดีกว่าระหว่าง (รายวัน × คืน) กับ (รายเดือน × คืน / 30) — แขกพักยาวจ่ายน้อยลง คุณเต็มห้อง' },
    monthly_rate: { fr: 'Tarif mensuel (USD pour 30 nuits)', th: 'อัตรารายเดือน (USD ต่อ 30 คืน)' },
    monthly_rate_eg: { fr: 'ex. 600 (= $20/nuit)', th: 'เช่น 600 (= $20/คืน)' },
    monthly_min_nights: { fr: 'Déclenché à (nuits)', th: 'เริ่มที่ (คืน)' },
    weekly_discount: { fr: 'Remise hebdomadaire (%)', th: 'ส่วนลดรายสัปดาห์ (%)' },
    weekly_min_nights: { fr: 'Hebdo déclenché à (nuits)', th: 'รายสัปดาห์เริ่มที่ (คืน)' },
    hourly_title: { fr: 'Location à l\'heure / day-use', th: 'เช่ารายชั่วโมง / day-use' },
    hourly_hint: { fr: 'Optionnel. Clients day-use, escales, courts séjours.', th: 'ไม่บังคับ แขก day-use ผู้แวะพัก พักสั้น' },
    hourly_desc: { fr: 'Définissez un prix horaire fixe (et/ou un tarif demi-journée). Quand un client réserve moins d\'heures que votre plafond day-use, le moins cher entre (horaire × heures) vs day_use_rate gagne automatiquement.', th: 'ตั้งราคาคงที่รายชั่วโมง (และ/หรืออัตราครึ่งวัน) เมื่อแขกจองน้อยกว่าเพดาน day-use ของคุณ ราคาที่ถูกกว่าระหว่าง (รายชั่วโมง × ชั่วโมง) กับ day_use_rate จะชนะอัตโนมัติ' },
    hourly_rate: { fr: 'Tarif horaire (USD)', th: 'อัตรารายชั่วโมง (USD)' },
    hourly_rate_eg: { fr: 'ex. 8 ($/heure)', th: 'เช่น 8 ($/ชั่วโมง)' },
    hourly_min: { fr: 'Min h', th: 'ชม.ต่ำสุด' },
    hourly_max: { fr: 'Max h', th: 'ชม.สูงสุด' },
    day_use_rate: { fr: 'Day-use forfait (USD)', th: 'Day-use คงที่ (USD)' },
    day_use_rate_eg: { fr: "ex. 35 (couvre jusqu'à 6h)", th: 'เช่น 35 (ครอบคลุมถึง 6 ชม.)' },
    day_use_max_hours: { fr: 'Day-use couvre (heures)', th: 'Day-use ครอบคลุม (ชั่วโมง)' },
    linked_packages_title: { fr: 'Packages liés', th: 'แพ็คเกจที่เชื่อมโยง' },
    linked_packages_desc: { fr: 'Cochez les packages à associer à cette chambre. Qty par défaut = capacité de la chambre (1 unité par client) ; modifiez manuellement pour les packages couple-only ou famille-only.', th: 'ติ๊กแพ็คเกจที่จะรวมกับห้องนี้ จำนวนเริ่มต้น = ความจุห้อง (1 หน่วยต่อแขก) ปรับด้วยตนเองสำหรับแพ็คเกจคู่หรือครอบครัว' },
    media_after_save: { fr: "Enregistrez d'abord la chambre, puis rouvrez-la pour téléverser photos et vidéos pour ce type spécifique.", th: 'บันทึกห้องก่อน จากนั้นเปิดอีกครั้งเพื่ออัพโหลดรูปและวิดีโอสำหรับประเภทเฉพาะ' },
  },

  booking: {
    back: { fr: 'Retour aux résultats', th: 'กลับสู่ผลการค้นหา' },
    show_map: { fr: 'Voir sur la carte', th: 'แสดงบนแผนที่' },
    amenities: { fr: 'Tous les équipements', th: 'สิ่งอำนวยความสะดวกทั้งหมด' },
    amenities_collapse: { fr: 'Voir moins', th: 'แสดงน้อยลง' },
    select_room: { fr: 'Choisissez votre chambre', th: 'เลือกห้องของคุณ' },
    no_rooms: { fr: 'Aucune chambre disponible', th: 'ไม่มีห้องว่าง' },
    try_dates: { fr: 'Essayez d\'autres dates ou un groupe plus petit.', th: 'ลองวันอื่นหรือจำนวนคนน้อยลง' },
    best_value: { fr: 'Meilleur rapport', th: 'คุ้มค่าที่สุด' },
    dorm_capacity: { fr: 'Dortoir', th: 'ห้องรวม' },
    free_cancel: { fr: 'Annulation gratuite', th: 'ยกเลิกฟรี' },
    escrow_short: { fr: 'Sous séquestre', th: 'อยู่ใน escrow' },
    before_pay_fees: { fr: '+ frais de paiement au checkout', th: '+ ค่าธรรมเนียมการชำระเงินที่ checkout' },
    select: { fr: 'Sélectionner', th: 'เลือก' },
    add_package: { fr: 'Ajouter un package ?', th: 'เพิ่มแพ็คเกจหรือไม่?' },
    guest_reviews: { fr: 'Avis clients', th: 'รีวิวแขก' },
    check_avail: { fr: 'Vérifier la disponibilité', th: 'ตรวจสอบความพร้อมใช้งาน' },
    too_many_guests: { fr: 'Cette chambre accueille jusqu\'à', th: 'ห้องนี้รองรับสูงสุด' },
    extra_bed_kid: { fr: "lit d'appoint pour enfant ≤", th: 'เตียงเสริมสำหรับเด็ก ≤' },
    guests_lower: { fr: 'invités. Réduisez le nombre ou choisissez une chambre plus grande.', th: 'แขก ลดจำนวนหรือเลือกห้องใหญ่กว่า' },
    subtotal: { fr: 'Sous-total', th: 'ยอดรวม' },
    fees_at_checkout: { fr: 'Frais de paiement ajoutés au checkout (gratuit avec Bitcoin Lightning).', th: 'ค่าธรรมเนียมการชำระเงินเพิ่มที่ checkout (ฟรีกับ Bitcoin Lightning)' },
    select_room_first: { fr: "Sélectionnez d'abord une chambre", th: 'กรุณาเลือกห้องก่อน' },
    too_many_guests_short: { fr: 'Trop d\'invités pour cette chambre', th: 'แขกมากเกินไปสำหรับห้องนี้' },
    reserve_now: { fr: 'Réserver maintenant', th: 'จองตอนนี้' },
    no_charge: { fr: 'Aucun débit pour le moment', th: 'ยังไม่มีการเรียกเก็บเงิน' },
    badge_cancel: { fr: 'Annulation gratuite avant le check-in', th: 'ยกเลิกฟรีก่อนเช็คอิน' },
    badge_escrow: { fr: 'Fonds sécurisés jusqu\'au check-out', th: 'เงินถูกเก็บปลอดภัยจนถึงเช็คเอาท์' },
    badge_verified: { fr: 'Propriété vérifiée STAYLO', th: 'ทรัพย์สินยืนยันโดย STAYLO' },
    need_help: { fr: 'Besoin d\'aide avec votre réservation ?', th: 'ต้องการความช่วยเหลือกับการจอง?' },
    slogan: { fr: 'Propriété des hôteliers, conçu pour l\'hospitalité', th: 'เป็นเจ้าของโดยเจ้าของโรงแรม สร้างเพื่อการบริการ' },
    hero_title: { fr: 'Trouvez des offres sur hôtels, resorts & plus', th: 'ค้นหาดีลโรงแรม รีสอร์ท และอื่นๆ' },
    hero_subtitle: { fr: 'Réservez directement chez les hôteliers — économisez jusqu\'à 20% vs autres plateformes', th: 'จองตรงกับเจ้าของโรงแรม — ประหยัดสูงสุด 20% เทียบกับแพลตฟอร์มอื่น' },
    where: { fr: 'Où allez-vous ?', th: 'คุณจะไปที่ไหน?' },
    search: { fr: 'Rechercher', th: 'ค้นหา' },
    tagline_highlight: { fr: 'Vous n\'êtes pas juste un partenaire — vous êtes la plateforme.', th: 'คุณไม่ใช่แค่พันธมิตร — คุณคือแพลตฟอร์ม' },
    tagline_body: { fr: 'STAYLO est la seule plateforme de booking détenue et gérée par les hôteliers.', th: 'STAYLO เป็นแพลตฟอร์มจองโรงแรมเดียวที่เป็นของและบริหารโดยเจ้าของโรงแรม' },
    tagline_cta: { fr: 'Réservez, partagez, gagnez — construisez un revenu passif éthique tout en faisant grandir une communauté qui place l\'hospitalité en premier.', th: 'จอง แชร์ รับเงิน — สร้างรายได้แบบ passive อย่างมีจริยธรรมพร้อมขยายชุมชนที่ให้ความสำคัญกับการบริการเป็นอันดับแรก' },
    popular_destinations: { fr: 'Destinations populaires en Thaïlande', th: 'จุดหมายปลายทางยอดนิยมในประเทศไทย' },
    explore_desc: { fr: 'Explorez les villes les plus réservées par les autres voyageurs', th: 'สำรวจเมืองยอดนิยมที่นักเดินทางอื่นจอง' },
    properties: { fr: 'propriétés', th: 'ทรัพย์สิน' },
    browse_all: { fr: 'Parcourir toutes les propriétés', th: 'ดูทรัพย์สินทั้งหมด' },
    properties_found: { fr: 'propriétés trouvées', th: 'พบทรัพย์สิน' },
    adult: { fr: 'adulte', th: 'ผู้ใหญ่' },
    adults: { fr: 'adultes', th: 'ผู้ใหญ่' },
    child: { fr: 'enfant', th: 'เด็ก' },
    children: { fr: 'enfants', th: 'เด็ก' },
    sort_recommended: { fr: 'Recommandés', th: 'แนะนำ' },
    sort_price_low: { fr: 'Prix : du moins cher au plus cher', th: 'ราคา: ต่ำ → สูง' },
    sort_price_high: { fr: 'Prix : du plus cher au moins cher', th: 'ราคา: สูง → ต่ำ' },
    sort_savings: { fr: 'Plus grosses économies', th: 'ประหยัดมากที่สุด' },
    flagship: { fr: 'Propriété phare — où tout a commencé', th: 'ทรัพย์สินเรือธง — จุดเริ่มต้นของทุกอย่าง' },
    staylo_hq: { fr: 'Siège STAYLO', th: 'สำนักงานใหญ่ STAYLO' },
    beachfront: { fr: 'En front de mer', th: 'ติดชายหาด' },
    exclusive: { fr: 'Exclu STAYLO — pas de markup OTA', th: 'เฉพาะ STAYLO — ไม่มี markup OTA' },
    save_with_staylo: { fr: 'Prix STAYLO', th: 'ราคา STAYLO' },
    popular: { fr: 'Populaire', th: 'ยอดนิยม' },
    you_save: { fr: 'Vous économisez', th: 'คุณประหยัด' },
    secure: { fr: 'Réservation sécurisée', th: 'การจองปลอดภัย' },
    verified: { fr: 'Propriétés vérifiées', th: 'ทรัพย์สินยืนยันแล้ว' },
    support: { fr: 'Support 24/7', th: 'รองรับ 24/7' },
    commission_note: { fr: '10% de commission seulement — le plus bas du secteur', th: 'ค่าคอมมิชชั่น 10% เท่านั้น — ต่ำสุดในอุตสาหกรรม' },
  },

  checkout: {
    signin_required: { fr: 'Connectez-vous pour réserver', th: 'เข้าสู่ระบบเพื่อจอง' },
    signin_desc: { fr: 'Vous avez besoin d\'un compte pour finaliser votre réservation.', th: 'คุณต้องมีบัญชีเพื่อทำการจองให้เสร็จสิ้น' },
    crypto_failed: { fr: 'Impossible de créer la facture Lightning', th: 'ไม่สามารถสร้าง Lightning invoice ได้' },
    crypto_no_invoice: { fr: 'Facture Lightning manquante — veuillez réessayer', th: 'Lightning invoice หายไป — โปรดลองอีกครั้ง' },
    err_hotelier_not_onboarded: { fr: "L'hôtelier n'a pas encore connecté de compte de payout. Réessayez plus tard ou contactez le support.", th: 'เจ้าของโรงแรมยังไม่ได้เชื่อมต่อบัญชีรับเงิน โปรดลองอีกครั้งหรือติดต่อ support' },
    err_hotelier_inactive: { fr: "Le compte de paiement de l'hôtelier n'est pas encore totalement actif. Votre réservation est en attente — réessayez bientôt.", th: 'บัญชีการชำระเงินของเจ้าของโรงแรมยังไม่เปิดใช้งานเต็มที่ การจองของคุณถูกพักไว้ — ลองอีกครั้งเร็วๆ นี้' },
    no_url: { fr: 'La session de paiement n\'a pas pu être créée. Réessayez.', th: 'ไม่สามารถสร้าง session การชำระเงินได้ ลองอีกครั้ง' },
    your_reference: { fr: 'Votre référence de réservation', th: 'หมายเลขอ้างอิงการจองของคุณ' },
    click_to_copy: { fr: 'Cliquez pour copier', th: 'คลิกเพื่อคัดลอก' },
    ref_note: { fr: 'Utilisez cette référence dans toute correspondance avec l\'hôtel ou STAYLO.', th: 'ใช้หมายเลขอ้างอิงนี้ในการติดต่อกับโรงแรมหรือ STAYLO' },
    staylo_commission: { fr: 'Commission STAYLO (10%)', th: 'ค่าคอมมิชชั่น STAYLO (10%)' },
    hotelier_receives: { fr: 'L\'hôtelier reçoit', th: 'เจ้าของโรงแรมได้รับ' },
    payment_method: { fr: 'Mode de paiement', th: 'วิธีการชำระเงิน' },
    coming_soon: { fr: 'Bientôt', th: 'เร็วๆ นี้' },
    free: { fr: 'Gratuit', th: 'ฟรี' },
    processing_fee: { fr: 'Frais de traitement', th: 'ค่าธรรมเนียมการประมวลผล' },
    total_you_pay: { fr: 'Vous payez', th: 'คุณจ่าย' },
    transparency_note: { fr: 'STAYLO ne majore jamais le prix de la chambre. Les frais de traitement couvrent uniquement les coûts de la passerelle de paiement — payez en Lightning pour les éviter.', th: 'STAYLO ไม่เคยบวก markup ราคาห้อง ค่าธรรมเนียมประมวลผลครอบคลุมเฉพาะค่าใช้จ่ายของเกตเวย์ชำระเงิน — จ่ายด้วย Lightning เพื่อข้ามค่าธรรมเนียม' },
  },

  survey: {
    savings_label: { fr: 'Vos économies annuelles estimées', th: 'การประหยัดต่อปีโดยประมาณ' },
    savings_detail: { fr: 'en passant à Staylo (10% vs 17%)', th: 'โดยเปลี่ยนมา Staylo (10% เทียบ 17%)' },
    step1_title: { fr: 'Combien payez-vous en commissions OTA par mois ?', th: 'คุณจ่ายค่าคอมมิชชั่น OTA ต่อเดือนเท่าไหร่?' },
    step1_subtitle: { fr: 'Estimez votre paiement mensuel total à Agoda, Booking.com, etc.', th: 'ประเมินการจ่ายเงินรวมต่อเดือนให้กับ Agoda, Booking.com ฯลฯ' },
    per_month: { fr: 'mois', th: 'เดือน' },
    annual_leaving: { fr: "C'est", th: 'นั่นคือ' },
    annual_leaving_suffix: { fr: 'par an qui quittent votre business.', th: 'ต่อปีที่ออกจากธุรกิจคุณ' },
    step2_title: { fr: 'Quel % de vos réservations passe par les OTA ?', th: '% การจองของคุณผ่าน OTA เท่าไหร่?' },
    step2_subtitle: { fr: 'À quel point dépendez-vous de plateformes comme Agoda ou Booking.com ?', th: 'คุณพึ่งพาแพลตฟอร์มอย่าง Agoda หรือ Booking.com แค่ไหน?' },
    dep_low: { fr: 'Majoritairement direct', th: 'ส่วนใหญ่ตรง' },
    dep_mid: { fr: 'Mix équilibré', th: 'ผสมสมดุล' },
    dep_high: { fr: 'Dépendant des OTA', th: 'พึ่งพา OTA' },
    dep_very_high: { fr: 'Fortement dépendant', th: 'พึ่งพามาก' },
    selected: { fr: 'sélectionné', th: 'เลือกแล้ว' },
    step4_title: { fr: 'Et si votre hôtel devenait actionnaire de Staylo ?', th: 'จะเป็นอย่างไรถ้าโรงแรมของคุณเป็นผู้ถือหุ้นใน Staylo?' },
    step4_subtitle: { fr: 'Votre business, votre outil — imaginez posséder une part de la plateforme qui travaille pour vous.', th: 'ธุรกิจของคุณ เครื่องมือของคุณ — ลองนึกภาพการเป็นเจ้าของแพลตฟอร์มที่ทำงานเพื่อคุณ' },
    step4_hint: { fr: 'Vous payez actuellement', th: 'คุณจ่ายในปัจจุบัน' },
    step4_hint2: { fr: 'en commissions — investissez l\'équivalent d\'1 seul mois.', th: 'ในค่าคอมมิชชั่น — ลงทุนเท่ากับเพียง 1 เดือน' },
    step4_question: { fr: 'Combien voudriez-vous investir ?', th: 'คุณอยากลงทุนเท่าไหร่?' },
    suggested: { fr: 'SUGGÉRÉ', th: 'แนะนำ' },
    your_investment: { fr: 'Votre investissement', th: 'การลงทุนของคุณ' },
    est_saving: { fr: 'Économie annuelle', th: 'การประหยัดรายปี' },
    in_year1: { fr: 'en année 1', th: 'ในปีที่ 1' },
    popup_title: { fr: 'Comment nous calculons vos économies', th: 'เราคำนวณการประหยัดของคุณอย่างไร' },
    popup_current: { fr: 'Ce que vous payez actuellement (OTA)', th: 'สิ่งที่คุณจ่ายตอนนี้ (OTA)' },
    popup_staylo: { fr: 'Avec Staylo (10% commission)', th: 'กับ Staylo (ค่าคอมมิชชั่น 10%)' },
    popup_staylo_calc: { fr: 'Mêmes réservations, mais seulement 10% au lieu de ~17%', th: 'การจองเดียวกัน แต่เพียง 10% แทนที่ ~17%' },
    year: { fr: 'an', th: 'ปี' },
    popup_saving: { fr: 'Votre économie annuelle', th: 'การประหยัดต่อปีของคุณ' },
    popup_note: { fr: 'C\'est ce qui reste dans VOTRE poche au lieu d\'aller aux actionnaires OTA.', th: 'นี่คือสิ่งที่อยู่ในกระเป๋าของคุณแทนที่จะไปสู่ผู้ถือหุ้น OTA' },
    popup_roi: { fr: 'Votre investissement de', th: 'การลงทุนของคุณ' },
    popup_roi2: { fr: 'se rembourse en', th: 'คืนทุนใน' },
    popup_months: { fr: 'mois', th: 'เดือน' },
    governance_title: { fr: '1 hôtel = 1 voix de gouvernance', th: '1 โรงแรม = 1 เสียงในการกำกับดูแล' },
    governance_desc: { fr: 'Peu importe le nombre de parts détenues. Chaque propriété a une voix égale.', th: 'ไม่ว่าคุณจะถือกี่หุ้น ทุกทรัพย์สินมีเสียงเท่าเทียมกัน' },
    step5_title: { fr: 'Presque fini ! Parlez-nous de votre propriété.', th: 'เกือบเสร็จแล้ว! บอกเราเกี่ยวกับทรัพย์สินของคุณ' },
    step5_subtitle: { fr: 'Nous vous contacterons avec les prochaines étapes pour devenir Founding Partner.', th: 'เราจะติดต่อคุณพร้อมขั้นตอนถัดไปในการเป็น Founding Partner' },
    property_name: { fr: 'Nom de la propriété', th: 'ชื่อทรัพย์สิน' },
    property_placeholder: { fr: 'ex. Sunset Beach Resort', th: 'เช่น Sunset Beach Resort' },
    your_email: { fr: 'Votre email', th: 'อีเมลของคุณ' },
    register_property: { fr: 'Enregistrer ma propriété', th: 'ลงทะเบียนทรัพย์สินของฉัน' },
    become_partner: { fr: 'Devenir Founding Partner', th: 'เป็น Founding Partner' },
  },
};

function apply(locale) {
  const p = path.join(ROOT, 'src', 'i18n', `${locale}.json`);
  const bundle = JSON.parse(fs.readFileSync(p, 'utf-8'));
  let count = 0;
  for (const [ns, keys] of Object.entries(T)) {
    bundle[ns] = bundle[ns] || {};
    for (const [k, v] of Object.entries(keys)) {
      const trans = v[locale];
      if (!trans) continue;
      bundle[ns][k] = trans;
      count++;
    }
  }
  fs.writeFileSync(p, JSON.stringify(bundle, null, 2) + '\n', 'utf-8');
  console.log(`  ${locale}.json: ${count} keys translated`);
}

console.log('[translate-batch2] applying batch 2/2 (dashboard, manage, booking, checkout, survey)…');
apply('fr');
apply('th');
console.log('[translate-batch2] done. Run sync next.');
